import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { RecoilWrapper } from "./components/RecoilWrapper/RecoilWrapper";
import Player from "./components/Player/Player";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <RecoilWrapper>
          {children}
        </RecoilWrapper>
      </body>
    </html>
  );
}
