import type { Metadata } from "next";
import "./globals.css";
import { RecoilWrapper } from "./components/RecoilWrapper/RecoilWrapper";
import Player from "./components/Player/Player";
import Header from "./components/Header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <RecoilWrapper>
          <Header />
          {children}
          <Player />
        </RecoilWrapper>
      </body>
    </html>
  );
}
